apiVersion: v1
kind: Pod
metadata:
  name: nginxwebproxy
  labels:
    role: nginxpod
spec:
  containers:
    - name: nginx
      image: nginx:1.16.0
      ports:
        - name: nginxport
          containerPort: 80
          protocol: TCP